/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package playkotlin

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val p1 = Person("Jane", "Doe", 24)
    println(p1.name)
    println(showFirstChar("ade"))
    println(p1.getAge())

    val (pi, e) = multiReturn()
    println(pi)
    println(e)

    val p2 = Person("John", "Doe", 32)
    if (p2 older p1) {
        println("infix works")
    }
}
